function [x_Data,y_Data]=generatebbox(xCG,yCG,width,length,ex,ey,exOrtho,eyOrtho)

x_Data(3) = xCG+ex*...
    (length/2)+...
    ((width)/2)*exOrtho;
y_Data(3) = yCG+ey*...
    (length/2)+...
    ((width)/2)*eyOrtho;
x_Data(4) = xCG+ex*...
    (length/2)-...
    ((width)/2)*exOrtho;
y_Data(4) = yCG+ey*...
    (length/2)-...
    ((width)/2)*eyOrtho;
x_Data(2) = xCG-ex*...
    (length/2)+...
    ((width)/2)*exOrtho;
y_Data(2) = yCG-ey*...
    (length/2)+...
    ((width)/2)*eyOrtho;
x_Data(1) = xCG-ex*...
    (length/2)-...
    ((width)/2)*exOrtho;
y_Data(1) = yCG-ey*...
    (length/2)-...
    ((width)/2)*eyOrtho;








end